# Project information
site_name: Multi tenancy CodeEngine/Serverless
site_url: https://karimdeif.github.io/multi-tenancy
site_author: TBD

# Repository
repo_name: Multi tenancy CodeEngine/Serverless
repo_url: https://github.com/karimdeif/multi-tenancy
edit_uri: edit/master/documentation
docs_dir: documentation

# Navigation
nav:
  - Introduction:
     - Architecture and projects: ./README.md
     - Sprint in week 41 serverless:
       - Objectives: ./serverless_sprint_week_41_objectives.md
       - Tasks: ./serverless_sprint_week_41_tasks.md
  - Labs: 
    - 1. Create an IBM Cloud account: ./create_ibmcloud_account.md
    - 2. Open IBM Cloud Shell: ./open_ibmcloud_shell.md
    - 3. Setup e-commerce example application on IBM Cloud: ./setup_application.md
    - 4. TBD: ./TBD.md
    - 5. TBD: ./TBD.md
  - Optional Labs: 
    - 1. Using App ID in a Vue.js frontend: ./vue-appid-frontend.md
    - 2. Vue.js using accesstoken to invoke Quarkus endpoints: ./vue-using-access-token-quarkus-endpoint.md
  - Additional Resources:
    - IBM Cloud Code Engine:
       - Examples on GitHub: https://github.com/IBM/CodeEngine
       - Code Engine CLI reference: https://cloud.ibm.com/docs/codeengine?topic=codeengine-cli
    - IBM Cloud:
       - IBM Cloud CLI: https://cloud.ibm.com/docs/cli?topic=cli-getting-started
    - Postgres: 
       - IBM Cloud "Cloud databases" CLI: https://cloud.ibm.com/docs/databases-cli-plugin?topic=databases-cli-plugin-cdb-reference
    - IBM Cloud App ID:
       - AppID API documentation: https://cloud.ibm.com/apidocs/app-id/management
       - AppID REST API (swagger-ui): https://us-south.appid.cloud.ibm.com/swagger-ui
    - Blog Posts:
       - Automated setup of AppID: https://suedbroecker.net/2021/10/06/automated-setup-of-an-ibm-cloud-app-id-instance-using-a-bash-script/
       - Quarkus externalization of container application: https://suedbroecker.net/2021/05/31/how-to-use-environment-variables-to-make-a-containerized-quarkus-application-more-flexible/
       - Vue.js externalization of container application: https://suedbroecker.net/2021/06/07/use-environment-variables-to-make-a-containerized-vue-js-frontend-application-more-flexible-and-deploy-it-to-code-engine/

## DO NOT CHANGE BELOW THIS LINE

# Copyright
# copyright: Copyright &copy; 2020 IBM Developer

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    # .svg automatically appended
    #logo: ibm_8bar_reverse_2
    logo: material/library
  features:
    # - navigation.tabs
    - navigation.instant
    # - navigation.expand
  palette:
    scheme: default
    primary: black
    accent: blue
  # palette:
  #  scheme: default
  #  primary: blue
  #  accent: blue
  # enable if you want to use a custom icon
  custom_dir: overrides

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/developerworks
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
