kind: ConfigMap
apiVersion: v1
metadata:
  name: frontend
data:
  VUE_APP_API_URL_PRODUCTS: URL_PRODUCTS_1
  VUE_APP_API_URL_ORDERS: URL_ORDERS_1
  VUE_APP_API_URL_CATEGORIES: URL_CATEGORIES_1
  VUE_APP_CATEGORY_NAME: APP_CATEGORY_NAME_1
  VUE_APP_HEADLINE: APP_HEADLINE_1
  VUE_APP_ROOT: APP_ROOT_1