# permissions for end users to edit ecommerceapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecommerceapplication-editor-role
rules:
- apiGroups:
  - saas.saas.ecommerce.sample.com
  resources:
  - ecommerceapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.saas.ecommerce.sample.com
  resources:
  - ecommerceapplications/status
  verbs:
  - get
