---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-backend
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "main"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: fail-on-lint-errors
      description: force failure of task when docker lint errors are found
      default: "true"
    - name: fail-on-scanned-issues
      description: force failure of task when vulnerability advisor scan issues are found
      default: "false"
    - name: path-to-context
      default: "."
    - name: path-to-dockerfile
      default: "."
    - name: dockerfile
      default: "Dockerfile"
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: registry-namespace
      description: container registry namespace
    - name: registry-create-namespace
      description: create container registry namespace if it doesn't already exists
      default: "true"
    - name: app-name
      description: application name
    - name: image-name
      description: image name
    - name: region
      description: region of application deployment
    - name: resource-group
      description: resource group for the application deployment
    - name: code-engine-project
      description: Code Engine project for the application deployment
    - name: service-bindings
      description: service binding JSON for the application deployment
      default: "{}"
    - name: port
      description: port where the application is listening
      default: "http1:8080"
    - name: health-endpoint
      description: application health endpoint, e.g. /health
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1. Default to 0
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: workspace-backend-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-backend-$(uid)
      spec:
        pipelineRef:
          name: pipeline-backend
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: fail-on-lint-errors
            value: $(params.fail-on-lint-errors)
          - name: fail-on-scanned-issues
            value: $(params.fail-on-scanned-issues)
          - name: path-to-context
            value: $(params.path-to-context)
          - name: path-to-dockerfile
            value: $(params.path-to-dockerfile)
          - name: dockerfile
            value: $(params.dockerfile)
          - name: registry-region
            value: $(params.registry-region)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: registry-create-namespace
            value: $(params.registry-create-namespace)
          - name: app-name
            value: $(params.app-name)
          - name: image-name
            value: $(params.image-name)
          - name: region
            value: $(params.region)
          - name: resource-group
            value: $(params.resource-group)
          - name: code-engine-project
            value: $(params.code-engine-project)
          - name: service-bindings
            value: $(params.service-bindings)
          - name: port
            value: $(params.port)
          - name: health-endpoint
            value: $(params.health-endpoint)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: workspace-backend
            persistentVolumeClaim:
              claimName: workspace-backend-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual-backend
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run-backend
spec:
  triggers:
    - binding:
        name: trigger-binding-manual-backend
      template:
        name: trigger-template-backend

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-commit-backend
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: branch
      value: "$(event.ref)"
    - name: revision
      value: "$(event.head_commit.id)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit-backend
spec:
  triggers:
    - binding:
        name: github-commit-backend
      template:
        name: trigger-template-backend

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: grit-or-gitlab-commit-backend
spec:
  params:
    - name: repository
      value: "$(event.repository.git_http_url)"
    - name: branch
      value: "$(event.ref)"
    - name: revision
      value: "$(event.checkout_sha)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: grit-or-gitlab-commit-backend
spec:
  triggers:
    - binding:
        name: grit-or-gitlab-commit-backend
      template:
        name: trigger-template-backend

---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-backend-tenant
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "main"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: fail-on-lint-errors
      description: force failure of task when docker lint errors are found
      default: "true"
    - name: fail-on-scanned-issues
      description: force failure of task when vulnerability advisor scan issues are found
      default: "false"
    - name: path-to-context
      default: "."
    - name: path-to-dockerfile
      default: "."
    - name: dockerfile
      default: "Dockerfile"
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: registry-namespace
      description: container registry namespace
    - name: registry-create-namespace
      description: create container registry namespace if it doesn't already exists
      default: "true"
    - name: app-name
      description: application name
    - name: image-name
      description: image name
    - name: region
      description: region of application deployment
    - name: resource-group
      description: resource group for the application deployment
    - name: code-engine-project
      description: Code Engine project for the application deployment
    - name: service-bindings
      description: service binding JSON for the application deployment
      default: "{}"
    - name: port
      description: port where the application is listening
      default: "http1:8080"
    - name: health-endpoint
      description: application health endpoint, e.g. /health
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1. Default to 0
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: workspace-backend-tenant-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-backend-tenant-$(uid)
      spec:
        pipelineRef:
          name: pipeline-backend-tenant
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: fail-on-lint-errors
            value: $(params.fail-on-lint-errors)
          - name: fail-on-scanned-issues
            value: $(params.fail-on-scanned-issues)
          - name: path-to-context
            value: $(params.path-to-context)
          - name: path-to-dockerfile
            value: $(params.path-to-dockerfile)
          - name: dockerfile
            value: $(params.dockerfile)
          - name: registry-region
            value: $(params.registry-region)
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: registry-create-namespace
            value: $(params.registry-create-namespace)
          - name: app-name
            value: $(params.app-name)
          - name: image-name
            value: $(params.image-name)
          - name: region
            value: $(params.region)
          - name: resource-group
            value: $(params.resource-group)
          - name: code-engine-project
            value: $(params.code-engine-project)
          - name: service-bindings
            value: $(params.service-bindings)
          - name: port
            value: $(params.port)
          - name: health-endpoint
            value: $(params.health-endpoint)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: workspace-backend-tenant
            persistentVolumeClaim:
              claimName: workspace-backend-tenant-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual-backend-tenant
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run-backend-tenant
spec:
  triggers:
    - binding:
        name: trigger-binding-manual-backend-tenant
      template:
        name: trigger-template-backend-tenant
