apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-backend
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "main"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1. Default to 0
      default: "0"
  workspaces:
    - name: workspace-backend
  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: git-clone-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: workspace
          workspace: workspace-backend
    - name: read-global-config
      taskRef:
        name: read-global-config
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
      workspaces:
        - name: workspace-backend
          workspace: workspace-backend
      runAfter: [git-clone-repo]
    - name: test-global-config
      taskRef:
        name: test-global-config
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
      workspaces:
        - name: workspace-backend
          workspace: workspace-backend
      runAfter: [read-global-config]
    - name: icr-execute-in-dind
      runAfter: [test-global-config]
      taskRef:
        name: icr-execute-in-dind
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: container-registry-apikey-secret-key
          value: "apikey"
        - name: registry-create-namespace
          value: "false"
        - name: registry-region
          value: "eu-de"
        - name: registry-namespace
          value: "multi-tenancy-example"
        - name: image-name
          value: "us.icr.io/multi-tenancy-example/multi-tenancy-backend:v2"
        - name: path-to-context
          value: "$(workspaces.workspace.path)/code/service-catalog"
        - name: path-to-dockerfile
          value: "./"
        - name: dockerfile
          value: "Dockerfile"
        - name: docker-commands
          value: |
            docker build --tag $IMAGE_NAME --file $PATH_TO_DOCKERFILE/$DOCKERFILE $PATH_TO_CONTEXT
            docker inspect $IMAGE_NAME
            docker push $IMAGE_NAME
        - name: pipeline-debug
          value: "true"
      workspaces:
        - name: source
          workspace: workspace-backend     
    - name: trigger-tenant-pipelines-backend
      taskRef:
        name: trigger-tenant-pipelines-backend
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
      workspaces:
        - name: workspace-backend
          workspace: workspace-backend
      runAfter: [icr-execute-in-dind]