apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-tenant-b
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "main"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: fail-on-lint-errors
      description: force failure of task when docker lint errors are found
      default: "true"
    - name: fail-on-scanned-issues
      description: force failure of task when vulnerability advisor scan issues are found
      default: "false"
    - name: path-to-context
      default: "."
    - name: path-to-dockerfile
      default: "."
    - name: dockerfile
      default: "Dockerfile"
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: registry-namespace
      description: container registry namespace
    - name: registry-create-namespace
      description: create container registry namespace if it doesn't already exists
      default: "true"
    - name: app-name
      description: application name
    - name: image-name
      description: image name
    - name: region
      description: region of application deployment
    - name: resource-group
      description: resource group for the application deployment
    - name: code-engine-project
      description: Code Engine project for the application deployment
    - name: service-bindings
      description: service binding JSON for the application deployment
      default: "{}"
    - name: port
      description: port where the application is listening
      default: "http1:8080"
    - name: health-endpoint
      description: application health endpoint, e.g. /health
      default: ""
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1. Default to 0
      default: "0"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-tenant-b
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tenant-b-parameters
spec:
  triggers:
    - binding:
        name: trigger-binding-tenant-b
      template:
        name: trigger-template-tenant-b