apiVersion: batch/v1
kind: Job
metadata:
  name: pg
spec:
  template:
    spec:
      containers:
      - name: pg
        image: bash
        args:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster
      restartPolicy: Never
  backoffLimit: 4