apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:  
  username: POSTGRES_USERNAME
  password: POSTGRES_PASSWORD
  url: POSTGRES_URL
  certificate.data: POSTGRES_CERTIFICATE_DATA