apiVersion: ibmcloud.ibm.com/v1
kind: Service
metadata:
  name: multi-tenancy-pg-ten-d
spec:
  plan: standard
  serviceClass: databases-for-postgresql
---
apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
  name: binding-multi-tenancy-pg-ten-d
spec:
  serviceName: multi-tenancy-pg-ten-d
  secretName: multi-tenancy-pg-ten-d-secret